cat > cloudbuild.yaml << 'YAML'
steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/daily-tech", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/daily-tech"]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - "gcloud"
      - "run"
      - "deploy"
      - "daily-tech"
      - "--image=gcr.io/$PROJECT_ID/daily-tech"
      - "--region=us-central1"
      - "--allow-unauthenticated"
YAML
