# cloudbuild.yaml
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/daily-tech', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/daily-tech']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        gcloud run deploy daily-tech \
          --image=gcr.io/$PROJECT_ID/daily-tech \
          --region=us-central1 \
          --platform=managed \
          --allow-unauthenticated \
          --add-cloudsql-instances=$INSTANCE_CONNECTION_NAME \
          --set-env-vars=DB_USER=$DB_USER,DB_PASS=$DB_PASS,DB_NAME=$DB_NAME,DB_HOST=/cloudsql/$INSTANCE_CONNECTION_NAME,SMTP_USER=$SMTP_USER,SMTP_PASSWORD=$SMTP_PASSWORD

timeout: 1800s
