cat > cloudbuild.yaml << 'YAML'
steps:
  # Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args: 
      - "build"
      - "-t"
      - "gcr.io/aerial-reef-478505-f6/daily-tech"
      - "."

  # Push the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args: 
      - "push"
      - "gcr.io/aerial-reef-478505-f6/daily-tech"

images:
  - "gcr.io/aerial-reef-478505-f6/daily-tech"
YAML
